#Actividad 2.2.2.
print("Bienvenido al Mundo de la Programación")
nom = input("Para comenzar, ingresa tu nombre:")
print(f"Bienvenido {nom}")
x = int(input("Ingresa un entero:"))
print("Resultado de la ecuación:",(x**2+3*x+1)/4)
rut = input("RUT:")
correo = input("Correo:")
telefono = input("Teléfono:")
print(f"Nombre:\t\t{nom}\nRUT:\t\t{rut}\nCorreo:\t\t{correo}\nTeléfono:\t{telefono}")
